# Generated by Django 5.1.4 on 2025-01-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('con_alcohol', 'Con Alcohol'), ('sin_alcohol', 'Sin Alcohol')], max_length=50)),
                ('preparacion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bebidas/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('tecnicas', 'Técnicas de Cocina'), ('herramientas', 'Herramientas Esenciales'), ('conservacion', 'Conservación de Alimentos')], max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
